version: '3.8'
services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: develop_node
    hostname: host-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secrets
    volumes:
      - ./data:/data/db
      - ./data/log:/var/log/mongodb
    ports:
      - "27017:27017"